services:
  # API Service
  - type: web
    name: scout-analytics-api
    runtime: node
    buildCommand: pnpm install && pnpm build
    startCommand: cd apps/api && pnpm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scout-analytics-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: API_PORT
        value: 3001

  # MCP SQLite Server
  - type: web
    name: scout-mcp-server
    runtime: node
    buildCommand: npm install -g @modelcontextprotocol/server-sqlite
    startCommand: mcp-server-sqlite --db-path /var/data/scout.db --port $PORT
    disk:
      name: scout-data
      mountPath: /var/data
      sizeGB: 1

databases:
  - name: scout-analytics-db
    databaseName: scout_analytics
    plan: starter